export const DATA_LOADED = 'DATA_LOADED';
export const DATA_LOADING = 'DATA_LOADING';
export const SELECT_DIVISION = 'SELECT_DIVISION';
export const SET_LEGACY_DATA = 'SET_LEGACY_DATA';
export const SET_LATEST_DATA = 'SET_LATEST_DATA';
export const SET_RELATIONSHIP_DATA = 'SET_RELATIONSHIP_DATA';
